run-name: Build ${{ inputs.plugin }} plugin | ${{ inputs.id }}
name: Build packages (on demand)

# This workflow runs when any of the following occur:
# - Run manually
# - Invoked from another workflow
on:
  workflow_dispatch:
    inputs:
      revision:
        description: "Revision"
        type: string
        default: "0"
      plugin:
        description: 'Name of the plugin to build'
        type: string
        required: true
        default: 'wazuh-indexer-setup'
      id:
        description: "ID used to identify the workflow uniquely."
        type: string
        required: false
  workflow_call:
    inputs:
      revision:
        description: "Revision"
        type: string
        default: "0"
      plugin:
        description: 'Name of the plugin to build'
        type: string
        required: true
        default: 'wazuh-indexer-setup'
      id:
        type: string
        required: false

# ==========================
# Bibliography
# ==========================
#
# * Reusable workflows: limitations
#   | https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations
# * Using matrix in reusable workflows:
#   | https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow
# * Reading input from the called workflow
#   | https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
# * Ternary operator
#   | https://docs.github.com/en/actions/learn-github-actions/expressions#example

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11 # TODO update to Java 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Get version
        id: version
        run: |
          echo "version=$(<VERSION)" >> "$GITHUB_OUTPUT"

      - name: Run `gradlew build`
        run: |
          cd ${{ inputs.plugin }}
          ./gradlew build -Dwazuh.version=${{ steps.version.outputs.version }}

      # - name: Test RPM package
      #   if: ${{ matrix.distribution == 'rpm' }}
      #   uses: addnab/docker-run-action@v3
      #   with:
      #     image: redhat/ubi9:latest
      #     options: -v ${{ github.workspace }}/artifacts/dist:/artifacts/dist
      #     run: |
      #       yum localinstall "/artifacts/dist/${{ steps.package.outputs.name }}" -y

      # - name: Test DEB package
      #   if: ${{ matrix.distribution == 'deb' }}
      #   run: |
      #     sudo dpkg -i "artifacts/dist/${{ steps.package.outputs.name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.plugin }}-${{ inputs.id }}-${{ inputs.revision }}.zip
          path: artifacts/dist/${{ steps.package.outputs.name }}
          if-no-files-found: error
