name: Continuous Integration

on:
    push:
        paths:
            - "plugins/**/*.java"     # Match changes in Java files.
            - "plugins/**/*.gradle"   # Match changes in Gradle configuration.
    pull_request:
        paths:
            - "plugins/**/*.java"     # Match changes in Java files.
            - "plugins/**/*.gradle"   # Match changes in Gradle configuration.

jobs:
    ci:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 2  # Fetch the last two commits to compare HEAD and HEAD~1

            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4
              with:
                  gradle-version: 7.5.1 # Optional, specify Gradle version if needed

            # Step to find which project folder contains modified files
            - name: Detect modified plugins
              id: detect_changes
              run: |
                # Ensure we can use HEAD~1, otherwise, we check for the existence of previous commits.
                if git rev-parse HEAD~1 >/dev/null 2>&1; then
                  CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
                else
                  # If there's no HEAD~1 (e.g., first commit), we use just HEAD.
                  CHANGED_FILES=$(git diff --name-only HEAD)
                fi

                # Check if any files are modified in wazuh-indexer-setup
                if echo "$CHANGED_FILES" | grep -q "^plugins/wazuh-indexer-setup/"; then
                  echo "wazuh-indexer-setup" >> affected_projects.txt
                fi
                
                # Check if any files are modified in wazuh-command-manager
                if echo "$CHANGED_FILES" | grep -q "^plugins/wazuh-command-manager/"; then
                  echo "wazuh-command-manager" >> affected_projects.txt
                fi

                # Output the list of affected projects
                if [ -f affected_projects.txt ]; then
                  echo "::set-output name=projects::$(cat affected_projects.txt | paste -sd,)"
                else
                  echo "::set-output name=projects::none"
                fi

            # Run tests for affected projects
            - name: Run tests for affected projects
              run: |
                if [[ "${{ steps.detect_changes.outputs.projects }}" != "none" ]]; then
                  for project in $(echo "${{ steps.detect_changes.outputs.projects }}" | tr ',' ' '); do
                    echo "Running tests for $project"
                    cd plugins/$project
                    ./gradlew check
                    cd - # Go back to the root folder
                  done
                else
                  echo "No changes in Java or Gradle files to test."
                fi
